---
- name: Manage APT
  ansible.builtin.include_tasks:
    file: manage-apt.yaml

- name: Configure network
  ansible.builtin.include_tasks:
    file: configure-network.yaml

- name: Secure system
  ansible.builtin.include_tasks:
    file: manage-security.yaml

- name: Manage certificates
  ansible.builtin.include_tasks:
    file: manage-certificates.yaml
