---
- name: Manage /etc/hosts entries for Vault servers
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for server in groups['vault'] %}
      {% set host = hostvars[server].ansible_host %}
      {{ host }} {{ dns_map[server] }}
      {% endfor %}
    insertbefore: EOF
