---
- name: Add HashiCorp APT repository
  ansible.builtin.include_role:
    name: apt-repository
  vars:
    apt_repository_hashicorp: true

- name: Install Vault
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - vault={{ vault_version }}
