---
- name: Destroy K3s cluster
  hosts: k3s
  become: true
  tasks:
    - name: Run K3s Uninstall script [server]
      when:
        - hostvars[inventory_hostname].vars.cluster_type == "k3s"
        - hostvars[inventory_hostname].vars.cluster_role == "server"
      ansible.builtin.command:
        cmd: k3s-uninstall.sh
        removes: /var/lib/rancher/k3s/*

    - name: Run K3s Uninstall script [agent]
      when:
        - hostvars[inventory_hostname].vars.cluster_type == "k3s"
        - hostvars[inventory_hostname].vars.cluster_role == "agent"
      ansible.builtin.command:
        cmd: k3s-agent-uninstall.sh
        removes: /var/lib/rancher/k3s/*

    - name: Remove user kubeconfig
      ansible.builtin.file:
        path: ~{{ ansible_user }}/.kube/config
        state: absent

    - name: Remove k3s install script
      ansible.builtin.file:
        path: /usr/local/bin/k3s-install.sh
        state: absent

    - name: Remove contents of K3s server location
      ansible.builtin.command:
        cmd: "rm -rf /var/lib/rancher"
        removes: "/var/lib/rancher"

    - name: Remove K3s config
      ansible.builtin.file:
        path: /etc/rancher/k3s/config.yaml
        state: absent

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
