---
- name: Configuring a Load Balancer servers
  hosts: load_balancer
  gather_facts: true
  become: true
  roles:
    - role: load-balancer-setup
  vars:
    master: load-balancer-1
    keepalived_vip: 10.0.30.20/16
