---
vault_version: 1.17.2-1
vault_keepalived_version: 1:2.2.7-1+b2

# User & Group
vault_user: vault
vault_group: vault

# Directories
vault_home_dir: /etc/vault.d
vault_data_dir: /opt/vault/data
vault_tls_dir: /opt/vault/tls
vault_keys_dir: /opt/vault/keys

# Cluster
vault_cluster_name: vault

# Keys
vault_key_shares: 3
vault_key_threshold: 2

# GCP Seal
vault_gcp_sealed: false
vault_gcp_project_id: ''
vault_gcp_location: europe-central2
vault_gcp_key_ring: ''
vault_gcp_crypto_key: ''

# TLS
vault_tls_cert_file: /opt/vault/tls/tls.crt
vault_tls_key_file: /opt/vault/tls/tls.key
